### ISSUE TITLE
keyword "contains" interrupts code foldings

### ISSUE THREAD

**Issue by sishue** [satamas/fortran-plugin#10]
When modules or subroutines have "contains" sections, the code foldings always stop at "contains". 

See the screenshots:

<img width="272" alt="screen shot 2017-09-25 at 13 32 22" src="https://user-images.githubusercontent.com/10587404/30793714-535a9a76-a189-11e7-99a0-d04e246009a8.png">
<img width="286" alt="screen shot 2017-09-25 at 13 32 14" src="https://user-images.githubusercontent.com/10587404/30793715-535aa980-a189-11e7-9bab-49dbc8537ec8.png">

**Comment by sgshulman** [comment]
Good day! We are not sure how to make comfortable folding in Fortran. Because in some situations it will work in a strange or uncomfortable way. Now we agree with you that folding of the whole program unit might be more comfortable than folding of a block. I've changed the folding. At the moment we can fold the whole program unit or subprograms part. But we can't fold the block.

Thank you for your response! We are always ready for any suggestions and comments.
