### ISSUE TITLE
Preprocessing directives were not formatted correctly, when i used the code formatter.

### ISSUE THREAD

**Issue by sofair** [satamas/fortran-plugin#21]
In my project, I use cpp directives to detect build configuration. When formatting code, there directives were not handled correctly.
```
PROGRAM TEST
#ifdef DEBUG
        PRINT*, "DEBUG"
#else
        PRINT*, "RELEASE"
#endif
END
```

**Comment by sizmailov** [comment]
I'm working on big project with tons of nested macros. It would be great to grey-out dead branches. It would make my work much easier. 

<details>
<summary> Example </summary>

```C++
#ifdef USE_MPI 
   #ifdef CUDA 
    ... 
   #endif 
... 
#else 
... 
#endif
```

</details>


I don't mind to implement it but I'm not sure how to approach the problem since I'm not quite familiar with IDEA plugin system. 

The problem seems to be harder than it looks at first, because macros effectively alters grammar and to properly expand macro plugin needs to evaluate expressions. Should it be resolved at "inspections" level? 

@satamas Can you give some directions here?

**Comment by satamas** [comment]
For full support of macros inspections is far too late. We have to process them during lexing and generate shadow elements with content produced by macros. This way psi will look like correct Fortran code for parser. 
This is already implemented in CLion for c/c++ and I've looked a little bit on related code. I want to say that it's a huge work to implement adequate macros support independently. Current implementation of macro support in CLion supports only c-like languages so re-using it is also difficult and requires write access to CLion source code.
I know that it will be amazing to implement this feature, but for now, I don't have time for such big things in the plugin.

**Comment by sizmailov** [comment]
Thanks for quick answer!
  
Is intermediate solution possible? E.g. handle only simple cases constants, simple expressions like `#define DEBUG=1`, `#ifdef DEBUG` ? 

Can meta comments be used to govern parser? 


```Fortran
#ifdef CUDA !!-idea-fortran: macro-branch-false
...
#else 
...
#endif
```

**Unrelated problem**


<details>
<summary>I have troubles with "runIde":</summary>

Internal error. Please report to http://jb.gg/ide/critical-startup-errors

java.lang.RuntimeException: Could not find installation home path. Please make sure bin/idea.properties is present in the installation directory.
    at com.intellij.openapi.application.PathManager.getHomePath(PathManager.java:97)
    at com.intellij.openapi.application.PathManager.getHomePath(PathManager.java:76)
    at com.intellij.openapi.application.PathManager.loadProperties(PathManager.java:416)
    at com.intellij.ide.Bootstrap.main(Bootstrap.java:19)
    at com.intellij.idea.Main.main(Main.java:71)

-----
JRE 11.0.4+11-post-Ubuntu-1ubuntu218.04.3 amd64 by Ubuntu
/usr/lib/jvm/java-11-openjdk-amd64

![image](https://user-images.githubusercontent.com/2975991/64973659-11736980-d8b4-11e9-8fc0-9e8c60775302.png)

</details>

I tried to switch JDK in settings, didn't help. I have `.local/share/JetBrains/Toolbox/apps/IDEA-U/ch-0/192.6603.28/idea.properties`. What am I doing wrong?

**Comment by satamas** [comment]
> Is intermediate solution possible? E.g. handle only simple cases constants, simple expressions like #define DEBUG=1, #ifdef DEBUG ?

I think yes, it's possible to support some directives and it should be rather simple compared to complete solutions.
Problem is that even simple constructions will work incorrectly in some cases like system defined macro variables or something like this. But on the other hand, it shouldn't be worse then it is now.

> Can meta comments be used to govern parser?
Probably yes, but that looks strange on the first look

> I have .local/share/JetBrains/Toolbox/apps/IDEA-U/ch-0/192.6603.28/idea.properties. What am I doing wrong?

`idea.properties` should be in `bin` directory, why they are in installation root? 
And it's better to move the discussion about that to IDEA support channel because several persons will receive emails about issue comments and they wouldn't be happy if we will continue discussion on the unrelated topic here.

**Comment by sizmailov** [comment]
I'm sorry for bombarding you with questions, but I need this feature quite badly :( 

I think I have broad idea how to implement simple macro support. Let me describe it here. Please correct me if I'm wrong:

I need to add a number of new lexer states: `WITHIN_CPP_IF_TRUE`, `WITHIN_CPP_IF_FALSE`, `WITHIN_CPP_ELSE_FALSE`, `WITHIN_CPP_IF_ELSE_FALSE`. 

 `*_TRUE` states will render all tokens as usual, while `*_FALSE` states render all tokens except as dead code.  

`#ifdef` pushes state, `#endif` pops state and  `#else` changes state appropriately. `#define`/`#undef` updates preprocessor list of constants.

The only problem is to decide whether we go to into `_TRUE` or `_FALSE` branch at `#ifdef`. We need to know dynamic information about preprocessor constants. Where should it be stored?  I'm puzzled.

`_FortranLexer` cannot hold it because it might be constructed at the middle of the file from saved "state". 

What did you mean by "shadow elements"?

**Comment by satamas** [comment]
I'll provide basic preprocessor support this week. I've decided to do this at upcoming JetBrains hackaton.

**Comment by satamas** [comment]
Polish this issue took more than a week, sorry, it's really hard to find time for this project. 
But it's published finally. Happy Holidays!
