### ISSUE TITLE
Plugin Error: Plugin "Fortran" is incompatible (until build 201.SNAPSHOT < PY-202.6397.98).

### ISSUE THREAD

**Issue by dipsecc** [satamas/fortran-plugin#65]
After updating the Pycharm to 202.6397.98, the Plugin "Fortran" has become incompatible and therefore I can not work with Fortran anymore:

"Plugin Error: Plugin "Fortran" is incompatible (until build 201.SNAPSHOT < PY-202.6397.98)."

Please advise.

**Comment by cmesse** [comment]
I get a similar message using the latest version of CLion, GCC and macOS Catalina:
"Incompatible (until build 201.SNAPSHOT < CL-202.6397.106)

I noticed that in the source under
fortran-plugin/gradle.properties

it says
buildNumber=SNAPSHOT
but
clionVersion=201.6487.17

could the problem be related to the fact that there is no actual number in buildNumber?

**Comment by arcsin20** [comment]
I've got the same error. The problem is in the src/main/resources/META-INF/plugin.xml file. until-build="201.*" on line 20 needs to be changed to "202.*". I've applied this change manually by editing the XML file within the JAR file locally and it seems to work.

**Comment by cmesse** [comment]
Yes, that worked. Thanks, good job!

**Comment by NeverGivinUp** [comment]
Same problem here. I can't find the "src"-folder refered to by @arcsin20. On my Windows system, changing the plugin.xml in the zips/jars  within the .CLion2019.3\config\plugins\fortran-plugin\lib in my user directory does not change anything.

**Comment by arcsin20** [comment]
Hi @NeverGivinUp, I think the .CLion2019.3 directory is just a configuration/cache directory (although I'm not sure about that). If you have CLion installed through the toolbox the directory you need is C:\Users\[username]\AppData\Local\JetBrains\Toolbox\apps\CLion\ch-0\[build number].plugins\lib . If you edit the plugin.xml within the fortran-plugin.jar here it should work.

**Comment by mkaraz** [comment]
Where is this plugin.xml file under Linux? My CLion is installed under /opt/clion-2020.1.1
I cannot find the file. Also checked my local user directory for a clion config directory/file  it doed not exist.

**Comment by arcsin20** [comment]
Hi @mkaraz , I think it should be in ```~/.local/share/JetBrains/CLion2020.2/fortran-plugin``` .The ```fortran-plugin.jar``` file contains the ```plugin.xml``` file.

**Comment by mkaraz** [comment]
Hi @arcsin20, thanks for the information. I found the directory. But I don't have the Fortran plugin anymore. Earlier I uninstalled it to have a fresh copy. The problem, right now, is that I cannot even see the plugin under Settings->PlugIns->Marketplace. I think because of the incompatibility issue, Fortran plugin doesn't show up here anymore. Do you have any ideas about how I can get the plugin back? Thanks.

**Comment by mkaraz** [comment]
I found the source code and downloaded, also tried to build it by "gradlew assemble" command as described in the GitHub page. 

I get the following error message: (I am not a JAVA person to straighten this out)
Can you please help. Thanks.

----------------------------------------------------------------------------
 $ gradlew assemble                                                        Downloading https://services.gradle.org/distributions/gradle-6.0.1-bin.zip                                              .........10%.........20%.........30%.........40%.........50%.........60%.........70%.........80%.........90%.........100%                                                                                                                                                                                                                                               Welcome to Gradle 6.0.1!                                                                                                                                                                                                                        Here are the highlights of this release:                                                                                 - Substantial improvements in dependency management, including                                                            - Publishing Gradle Module Metadata in addition to pom.xml                                                              - Advanced control of transitive versions                                                                               - Support for optional features and dependencies                                                                        - Rules to tweak published metadata                                                                                   - Support for Java 13                                                                                                   - Faster incremental Java and Groovy compilation                                                                        - New Zinc compiler for Scala                                                                                           - VS2019 support                                                                                                        - Support for Gradle Enterprise plugin 3.0                                                                                                                                                                                                     For more details see https://docs.gradle.org/6.0.1/release-notes.html                                                                                                                                                                           Starting a Gradle Daemon (subsequent builds will be faster)                                                                                                                                                                                     > Configure project :                                                                                                   [gradle-intellij-plugin :fortran-plugin] Cannot find alternate SDK path: debugger/lib/clion-201.6487.17. Default IDEA will be used : /home/karaz/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/ideaIC/LATEST-EAP-SNAPSHOT/4fe93bb81525f2fa7a6f0fd7ba41c3b9cce9e8b6/ideaIC-LATEST-EAP-SNAPSHOT                                                          [gradle-intellij-plugin :fortran-plugin] Cannot find alternate SDK path: debugger/lib/clion-201.6487.17. Default IDEA will be used : /home/karaz/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/ideaIC/LATEST-EAP-SNAPSHOT/4fe93bb81525f2fa7a6f0fd7ba41c3b9cce9e8b6/ideaIC-LATEST-EAP-SNAPSHOT                                                                                                                                                                                  > Task :generateFortranLexer                                                                                            Reading "/home/karaz/fortran-plugin-master/src/main/kotlin/org/jetbrains/fortran/lang/lexer/FortranLexer.flex"                                                                                                                                  Warning : Macro "EOL_ESC" has been declared but never used.                                                                                                                                                                                     Warning : Macro "CPP" has been declared but never used.                                                                                                                                                                                         Warning : Macro "CPPCOMMENT" has been declared but never used.                                                                                                                                                                                  Warning in file "/home/karaz/fortran-plugin-master/src/main/kotlin/org/jetbrains/fortran/lang/lexer/FortranLexer.flex" (line 244):                                                                                                              Expression matches the empty string, which may lead to non-termination.                                                     {DIRECTIVE_CONTENT} {return DIRECTIVE_CONTENT; }                                                                    Constructing NFA : 2,748 states in NFA                                                                                  Converting NFA to DFA :                                                                                                 .............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................                                                                           2467 states before minimization, 577 states in minimized DFA                                                            Writing code to "/home/karaz/fortran-plugin-master/src/gen/org/jetbrains/fortran/lang/lexer/_FortranLexer.java"                                                                                                                                 > Task :generateFortranParser FAILED                                                                                    Exception in thread "main" java.lang.NoClassDefFoundError: it/unimi/dsi/fastutil/Hash$Strategy                                  at com.intellij.core.CoreFileTypeRegistry.<init>(CoreFileTypeRegistry.java:23)                                          at com.intellij.core.CoreApplicationEnvironment.<init>(CoreApplicationEnvironment.java:83)                              at com.intellij.core.CoreApplicationEnvironment.<init>(CoreApplicationEnvironment.java:74)                              at org.intellij.grammar.LightPsi$MyParsing.<init>(LightPsi.java:166)                                                    at org.intellij.grammar.LightPsi.<clinit>(LightPsi.java:65)                                                             at org.intellij.grammar.Main.main(Main.java:49)                                                                 Caused by: java.lang.ClassNotFoundException: it.unimi.dsi.fastutil.Hash$Strategy                                                at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)                              at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)                           at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)                                                      ... 6 more                                                                                                                                                                                                                              FAILURE: Build failed with an exception.                                                                                                                                                                                                        * What went wrong:                                                                                                      Execution failed for task ':generateFortranParser'.                                                                     > Process 'command '/usr/lib/jvm/java-11-openjdk-amd64/bin/java'' finished with non-zero exit value 1                                                                                                                                           * Try:                                                                                                                  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.                                                                                                                                                                                                                    * Get more help at https://help.gradle.org                                                                                                                                                                                                      Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.                             Use '--warning-mode all' to show the individual deprecation warnings.                                                   See https://docs.gradle.org/6.0.1/userguide/command_line_interface.html#sec:command_line_warnings                                                                                                                                               BUILD FAILED in 2m 18s                                                                                                  2 actionable tasks: 2 executed

**Comment by mkaraz** [comment]
sorry,  next line characters are messed up since I copied from linux

**Comment by cmesse** [comment]
I also tried that and failed. Turns out, this is not necessary. 

Step 1: execute **find . -name fortran-plugin.jar** in your unix home directory to find out where CLion installs the arcive.
Step 2: copy it to a save enviribment, e.g. a directory you call /tmp/fortran-plugin
Step 3: make sure that $JAVA_HOME/bin is in your environment variable, e.g. by calling export **PATH=$JAVA_HOME/bin:$PATH**, you need to know of course where you have installed Java
Step 4: extract the archive **cd /tmp/fortran-plugin && jar xf  fortran-plugin.jar **
Step 5: locate the file plugin.xml and edit it
Step 6:  remove the file /tmp/fortran-plugin/fortran-plugin.jar, cd to /tmp and recompress it using **tar cvf fortran_plugin.jar fortran-plugin**
Step 7: copy the newly jar file into the original directory where Clion puts it.

Worked for me on macOS, should be the same on Linux.

**Comment by arcsin20** [comment]
If you have uninstalled the plugin, I think you will have to downgrade to 2020.1 to reinstall it.

**Comment by cmesse** [comment]
If it helps, this is my repacked file.

[fortran-plugin.jar.zip](https://github.com/satamas/fortran-plugin/files/5053649/fortran-plugin.jar.zip)

**Comment by mkaraz** [comment]
@cmesse thanks, I will try

**Comment by satamas** [comment]
Hi all. Sorry for this delay, I've uploaded new version of Fortran plugin that is compatible with latest IDE
